### ISSUE TITLE
[C4GT Community]: Create a CONTRIBUTING guideline

### ISSUE THREAD

**Issue by codecakes** [Xcov19/project-healthcare#20]
## Description

For first-timer and general contributions, it should be easy to find out how to start contributing to the project. a standard community guideline, as a `CONTRIBUTING.md` is need at project root. 

See a [guideline given out by github](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)

## Goals
- [x] Document a first timer approach to contributing
- [ ] Cover a coherent setup, testing, style guide and coding convention guide

Some instance of good contribution guidelines are given in these projects:

1. https://github.com/rails/rails/blob/main/CONTRIBUTING.md
2. https://github.com/opengovernment/opengovernment/blob/master/CONTRIBUTING.md

### Expected Outcome

A CONTRIBUTING.md file

### Implementation Details

- [x] Cover How to contribute 
- [x] Include  setup, testing, style guide and coding convention 
- [ ] Include section to cover OpenAPI intro and what our apis cover
- [ ] Include FAQ style section

### Product Name

project-healthcare

### Organisation Name

XCoV19

### Domain

Healthcare

### Tech Skills Needed

Flask, Markdown, Python

### Mentor(s)

@codecakes 

### Complexity

Medium

### Category

Documentation

### Sub-Category

Contributing

**Comment by Aman1919** [comment]
@codecakes I like to work on this issue.

**Comment by codecakes** [comment]
> @codecakes I like to work on this issue.

@Aman1919 have a look at https://github.com/Xcov19/project-healthcare/pull/23

You can enrich this pr with the missing parts that are in the ✅ checklist mentioned in the details here.

**Comment by barkhaaroraa** [comment]
are there any other changes/topics that need to be added to #23 so as to close this issue?

**Comment by codecakes** [comment]
> * [ ]  Include section to cover OpenAPI intro and what our apis cover
>         
>       
>   
>       Create an issue with the title Include section to cover OpenAPI intro and what our apis cover. Press Enter to convert to an issue instantly. Press Option-Enter to open the create new issue form in the current tab. Press Shift-Enter to open the create new issue form.
> * [ ]  Include FAQ style section

@barkhaaroraa you can run the instance locally or checkout the sandbox instance on [Render](https://project-healthcare.onrender.com/docs) and address these points and refer back to this issue
