### ISSUE TITLE
[C4GT Community]: Remove commented out line in pyproject.toml and setup project in your local

### ISSUE THREAD

**Issue by codecakes** [Xcov19/project-healthcare#52]
## Description
Project setup has become easier with steps outlined in [CONTRIBUTING](https://github.com/Xcov19/project-healthcare/blob/main/CONTRIBUTING.md)

There is no need for commented out dev groups in pyporject.toml

## Goals
- [ ] Remove the commented out line
- [ ] Ensure project is setup and runs successfully on your local

See [CONTRIBUTING](https://github.com/Xcov19/project-healthcare/blob/main/CONTRIBUTING.md)

### Expected Outcome

Project is setup and runs locally

### Implementation Details

Remove the commented out line

### Mockups/Wireframes

See: https://github.com/Xcov19/project-healthcare/issues/26#issuecomment-2315647630

### Product Name

project-healtlhcare

### Organisation Name

XCoV19

### Domain

Healthcare

### Tech Skills Needed

Python

### Mentor(s)

@codecakes 

### Complexity

Low

### Category

Backend, Beginner Friendly, Documentation, Maintenance, Testing

**Comment by Amrit02102004** [comment]
Can I be assigned this issue 
I will try doing it

**Comment by codecakes** [comment]
> [Amrit02102004](/Amrit02102004)
> Can I be assigned this issue I will try doing it

@Amrit02102004 Sure, go ahead!
